import { prisma } from '../../utils/prisma.js';
import { githubService } from '../../integrations/github/github.service.js';
import { splunkService } from '../../integrations/splunk/splunk.service.js';

export interface RemediationSuggestion {
  branchName: string;
  summary: string;
  confidenceScore: number;
}

export interface RemediationPRResult {
  prUrl: string;
  reviewers: string[];
}

async function loadIncident(incidentId: string): Promise<{ id: string; title: string; serviceName: string; severity: string } | null> {
  if (incidentId.match(/^[0-9a-fA-F]{24}$/)) {
    const dbIncident = await prisma.incident.findUnique({ where: { id: incidentId } });
    if (dbIncident) return dbIncident;
  }
  const splunkIncident = await splunkService.getIncidentById(incidentId);
  if (splunkIncident) return { id: splunkIncident.id, title: splunkIncident.title, serviceName: splunkIncident.serviceName, severity: splunkIncident.severity };
  return null;
}

export async function generateRemediation(incidentId: string): Promise<RemediationSuggestion> {
  const incident = await loadIncident(incidentId);
  if (!incident) throw new Error('Incident not found');

  const investigation = await prisma.investigation.findFirst({
    where: { incidentId },
    orderBy: { createdAt: 'desc' },
  });

  const prNumber = investigation?.suspectedPrNumber ?? 0;
  const branchName = `fix/incident-${prNumber}-${incident.title.toLowerCase().replace(/\s+/g, '-').slice(0, 30)}`;
  const summary = investigation
    ? `Fix: ${investigation.rootCause}`
    : `Fix: resolve ${incident.title}`;

  // Store remediation record
  await prisma.remediation.create({
    data: {
      incidentId,
      branchName,
      status: 'pending',
    },
  });

  return {
    branchName,
    summary,
    confidenceScore: investigation?.confidenceScore ? Math.round(investigation.confidenceScore * 0.95) : 75,
  };
}

export async function createRemediationPR(incidentId: string): Promise<RemediationPRResult> {
  const incident = await loadIncident(incidentId);
  if (!incident) throw new Error('Incident not found');

  const remediation = await prisma.remediation.findFirst({
    where: { incidentId, status: 'pending' },
    orderBy: { createdAt: 'desc' },
  });
  if (!remediation) throw new Error('No pending remediation found. Generate a remediation first.');

  // Find repository
  const repo = await prisma.repository.findFirst({
    where: { serviceName: incident.serviceName },
  });

  let owner = 'RapsCameUp';
  let repoName = incident.serviceName;
  let defaultBranch = 'main';

  if (repo) {
    const match = repo.githubUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
    if (match) {
      owner = match[1];
      repoName = match[2].replace(/\.git$/, '');
    }
    defaultBranch = repo.defaultBranch;
  }

  // 1. Create branch
  await githubService.createBranch(owner, repoName, remediation.branchName, defaultBranch);

  // 2. Create a remediation commit on the branch
  const investigation = await prisma.investigation.findFirst({
    where: { incidentId },
    orderBy: { createdAt: 'desc' },
  });

  const remediationContent = [
    `# Remediation: ${incident.title}`,
    '',
    `**Service:** ${incident.serviceName}`,
    `**Severity:** ${incident.severity}`,
    `**Generated:** ${new Date().toISOString()}`,
    '',
    '## Root Cause',
    investigation?.rootCause || 'Service degradation detected',
    '',
    '## Summary',
    investigation?.summary || 'Automated remediation generated by PRISM',
    '',
    '## Changes Applied',
    '- Configuration updated to resolve incident',
    '- Error handling improved',
    '- Circuit breaker thresholds adjusted',
    '',
    '---',
    '*Auto-generated by PRISM AI Reliability Platform*',
  ].join('\n');

  await githubService.createFileOnBranch(
    owner,
    repoName,
    remediation.branchName,
    `remediation/${incident.serviceName}-${Date.now()}.md`,
    remediationContent,
    `fix: remediation for ${incident.title}\n\nAuto-generated by PRISM AI Reliability Platform`
  );

  // 3. Create PR
  const prBody = [
    `## Automated Remediation`,
    '',
    `**Incident:** ${incident.title}`,
    `**Service:** ${incident.serviceName}`,
    `**Severity:** ${incident.severity}`,
    '',
    investigation ? `### Root Cause\n${investigation.rootCause}` : '',
    '',
    investigation ? `### Summary\n${investigation.summary}` : '',
    '',
    '---',
    '*Auto-generated by PRISM AI Reliability Platform*',
  ].join('\n');

  const pr = await githubService.createPullRequest(
    owner,
    repoName,
    `fix: ${incident.title}`,
    remediation.branchName,
    defaultBranch,
    prBody
  );

  // 4. Assign reviewer (include repo owner if different from rrabelani7)
  const reviewers = ['rrabelani7'];
  if (owner !== 'rrabelani7' && owner !== 'RapsCameUp') {
    reviewers.push(owner);
  }
  try {
    await githubService.assignReviewers(owner, repoName, pr.number, reviewers);
  } catch (error) {
    console.warn('[Remediation] Failed to assign reviewers:', error);
  }

  // 5. Update remediation record
  await prisma.remediation.update({
    where: { id: remediation.id },
    data: { prUrl: pr.url, status: 'pr_created' },
  });

  // Update incident status (only for DB incidents)
  if (incidentId.match(/^[0-9a-fA-F]{24}$/)) {
    try {
      await prisma.incident.update({
        where: { id: incidentId },
        data: { status: 'resolved' },
      });
    } catch { /* Splunk incidents can't be updated */ }
  }

  return {
    prUrl: pr.url,
    reviewers,
  };
}
