/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRepositoriesRouteImport } from './routes/_app.repositories'
import { Route as AppRemediationRouteImport } from './routes/_app.remediation'
import { Route as AppPrTracebackRouteImport } from './routes/_app.pr-traceback'
import { Route as AppInvestigationsRouteImport } from './routes/_app.investigations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app.incidents.index'
import { Route as AppIncidentsIdRouteImport } from './routes/_app.incidents.$id'

const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppRemediationRoute = AppRemediationRouteImport.update({
  id: '/remediation',
  path: '/remediation',
  getParentRoute: () => AppRoute,
} as any)
const AppPrTracebackRoute = AppPrTracebackRouteImport.update({
  id: '/pr-traceback',
  path: '/pr-traceback',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/agents': typeof AppAgentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/investigations': typeof AppInvestigationsRoute
  '/pr-traceback': typeof AppPrTracebackRoute
  '/remediation': typeof AppRemediationRoute
  '/repositories': typeof AppRepositoriesRoute
  '/settings': typeof AppSettingsRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/agents': typeof AppAgentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/investigations': typeof AppInvestigationsRoute
  '/pr-traceback': typeof AppPrTracebackRoute
  '/remediation': typeof AppRemediationRoute
  '/repositories': typeof AppRepositoriesRoute
  '/settings': typeof AppSettingsRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/incidents': typeof AppIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/investigations': typeof AppInvestigationsRoute
  '/_app/pr-traceback': typeof AppPrTracebackRoute
  '/_app/remediation': typeof AppRemediationRoute
  '/_app/repositories': typeof AppRepositoriesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/request-access'
    | '/agents'
    | '/dashboard'
    | '/investigations'
    | '/pr-traceback'
    | '/remediation'
    | '/repositories'
    | '/settings'
    | '/incidents/$id'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/request-access'
    | '/agents'
    | '/dashboard'
    | '/investigations'
    | '/pr-traceback'
    | '/remediation'
    | '/repositories'
    | '/settings'
    | '/incidents/$id'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/request-access'
    | '/_app/agents'
    | '/_app/dashboard'
    | '/_app/investigations'
    | '/_app/pr-traceback'
    | '/_app/remediation'
    | '/_app/repositories'
    | '/_app/settings'
    | '/_app/incidents/$id'
    | '/_app/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RequestAccessRoute: typeof RequestAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/remediation': {
      id: '/_app/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof AppRemediationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pr-traceback': {
      id: '/_app/pr-traceback'
      path: '/pr-traceback'
      fullPath: '/pr-traceback'
      preLoaderRoute: typeof AppPrTracebackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations': {
      id: '/_app/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof AppInvestigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvestigationsRoute: typeof AppInvestigationsRoute
  AppPrTracebackRoute: typeof AppPrTracebackRoute
  AppRemediationRoute: typeof AppRemediationRoute
  AppRepositoriesRoute: typeof AppRepositoriesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppPrTracebackRoute: AppPrTracebackRoute,
  AppRemediationRoute: AppRemediationRoute,
  AppRepositoriesRoute: AppRepositoriesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIncidentsIdRoute: AppIncidentsIdRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RequestAccessRoute: RequestAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
